[default]
src = 'src'
libs = ['lib']

remappings = [
    "forge-std=lib/forge-std/src", 
    "solmate=lib/solmate/src",
    "openzeppelin=lib/openzeppelin-contracts/contracts",
    "openzeppelin-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts/",
    "uniswap-lib=lib/solidity-lib/contracts/libraries",
    "uniswap-v2-core=lib/v2-core/contracts",
    "uniswap-v2-periphery=lib/v2-periphery/contracts"
]